### ISSUE TITLE
Facilitate managing a user's sites from their profile

### ISSUE THREAD

**Issue by johnbillion** [stuttter/wp-user-profiles#12]
Myself and @shadyvb have been doing some work relating to bulk managing users, particularly on multisite.

Bulk managing a site's users is covered by https://core.trac.wordpress.org/ticket/40265.

Bulk managing a user's sites can be covered by the `Sites` tab in WP User Profiles if it's adapted to show all sites on the network and enable a user to be added, removed, or have their role changed.

Shady has started some work on this.

**Comment by JJJ** [comment]
Merged!

Thanks @johnbillion and @shadyvb.
