### ISSUE TITLE
Calling action add_meta_boxes with wrong parameter type WP_User

### ISSUE THREAD

**Issue by dnaber-de** [stuttter/wp-user-profiles#17]
WP User Profiles calls the WP core action `add_meta_boxes` in a wrong way:

```
$user = wp_user_profiles_get_user_to_edit();
do_action( 'add_meta_boxes', get_current_screen()->id, $user );
```
(See [admin.php:272](https://github.com/stuttter/wp-user-profiles/blob/master/wp-user-profiles/includes/admin.php#L272))

As `wp_user_profiles_get_user_to_edit()` returns `WP_User`, the second parameter passed to every action listener is of this very type whereas WP core passes a parameter of type `WP_Post`. (See [wp-admin/edit-form-advanced.php](https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-form-advanced.php#L317-L325))

This causes a fatal error when type hinting `WP_Post` in an action listener but forces pretty much every listener (type hinted or not) to do an argument validation and handle that exceptional case.

I would suggest to completely remove this action call or at least pass something like a `NullPost` as parameter to don't violate the interface that is suggested by WP core.

**Comment by johnbillion** [comment]
This parameter can be any type, not just a `WP_Post`, so it can't be type hinted. For example, it's a `WP_Comment` on the comment editing screen.

Unfortunately the core documentation for this parameter is incorrect because it _does_ state that it's a `WP_Post`.

**Comment by johnbillion** [comment]
https://core.trac.wordpress.org/ticket/43229
