### ISSUE TITLE
Broken BuddyPress integration

### ISSUE THREAD

**Issue by slaFFik** [stuttter/wp-user-profiles#18]
Related: https://wordpress.org/support/topic/not-compitable-with-latest-buddypress-2-8-x/

![image](https://user-images.githubusercontent.com/282234/36537367-9471a20a-17d8-11e8-8ffb-1c0ad3cc2ad5.png)

Also, no Avatar management in the sidebar as per screenshot from your readme.

**Comment by JJJ** [comment]
Avatar Management requires WP User Avatars.

Those tabs are no good though. I'll look into it.
