### ISSUE TITLE
Fatal error: unsupported operand types

### ISSUE THREAD

**Issue by dlh01** [stuttter/wp-user-profiles#23]
A fatal error can occur in this logic: 

https://github.com/stuttter/wp-user-profiles/blob/b4be6a7c62b70bf8f4808e554033044c2d959946/wp-user-profiles/includes/metaboxes/sites-list.php#L315-L318 

when `$sites` is populated but the network requests for `$roles` fail, leaving `$roles` an empty array.

```
PHP Warning: array_intersect_key(): at least 2 parameters are required, 0 given in [...]/wp-user-profiles/includes/metaboxes/sites-list.php on line 318
PHP Fatal error: Uncaught Error: Unsupported operand types in [...]/wp-user-profiles/includes/metaboxes/sites-list.php on line 318
```

I'm happy to submit a PR, but I'm unsure what the desired fallback behavior should be, particularly if `$cache_ttl` remains a day.

**Comment by JJJ** [comment]
Seeing:

```
PHP message: PHP Warning:  array_intersect_key(): at least 2 parameters are required, 1 given in plugins/wp-user-profiles/wp-user-profiles/includes/metaboxes/sites-list.php on line 324
```

Fix imminent.
