### ISSUE TITLE
Plugin causing ACF assets to enqueue on frontend

### ISSUE THREAD

**Issue by Log1x** [stuttter/wp-user-profiles#28]
I'm having a strange issue where wp-user-profiles is causing ACF to load a ton of admin assets onto the frontend.

The issue goes away by removing the following hook:

```
remove_filter('wp_user_profiles_show_other_section', 'wp_user_profiles_has_profile_actions');
```

I'm not familiar with a lot of the user-based hooks so I'm not sure where the issue is stemming from. It could also be a problem with ACF – but I have never seen the issue occur with any other plugin so I'd figure I'd start here.

**Comment by JJJ** [comment]
Likely related to #29. Expecting this to be fixed via #30 in the next release.

Thanks for creating this issue @Log1x 💫
