### ISSUE TITLE
wp_user_profiles_has_profile_actions() causes fatal error if hooked callbacks use admin-only functions

### ISSUE THREAD

**Issue by nickcernis** [stuttter/wp-user-profiles#29]
WP User Profiles 2.2.0 causes a fatal error if a theme/plugin hooks actions to `show_user_profile` or `edit_user_profile` that use functions that are not intended to run outside of the user profile page.

Introduced in https://github.com/stuttter/wp-user-profiles/commit/ffafeb8fd5a3c4095cd3d41f58749d0b03295aa6.

Example with Genesis, which defines a `genesis_meta_boxes()` function only if `is_admin()` is true and uses it in the show_user_profile/edit_user_profile hooks:

<img width="816" alt="Screen Shot 2020-06-02 at 12 17 22" src="https://user-images.githubusercontent.com/647669/83510415-4587cc80-a4cd-11ea-92f8-0ddde6ae522e.png">

## To reproduce
1. Activate TwentyTwenty.
2. Add this code to `functions.php`:

```php
add_action( 'show_user_profile', 'custom_wp_user_profiles_bug' );
function custom_wp_user_profiles_bug() {
	echo $GLOBALS['current_screen']->in_admin(); // Or any function that is usually only available on the user profile page.
}
```

You will see `Call to a member function in_admin() on null` on the front-end and back-end of your site with WP User Profiles 2.2.0 active.

I have to do this before the `custom_wp_user_profiles_bug()` function will run and generate the expected output (`1`) on the “Other” tab:

```php
remove_filter( 'wp_user_profiles_show_other_section', 'wp_user_profiles_has_profile_actions' );
add_filter( 'wp_user_profiles_show_other_section', '__return_true' );
```

<img width="592" alt="Screen Shot 2020-06-02 at 12 56 47" src="https://user-images.githubusercontent.com/647669/83512467-89c89c00-a4d0-11ea-906d-256c3c8402b7.png">

## Impact
`show_user_profile` and `edit_user_profile` do not normally fire outside the user profile page by default in core, so introducing that behavior here is unexpected.

The Genesis Framework includes hooks for `show_user_profile` and `edit_user_profile` that use a function named `genesis_meta_boxes()` that is only defined if `is_admin()` is true.

Genesis users will not be able to use WP User Profiles 2.2.0 without seeing a fatal error, as reported at https://wordpress.org/support/topic/2-2-0-and-genesis-framework/.

**Comment by JJJ** [comment]
Hey @nickcernis, thank you for this helpful and detailed issue.

I'll make sure this gets resolved ASAP.

**Comment by JJJ** [comment]
2.2.1 is released today to fix this issue. Thank you again.
