### ISSUE TITLE
Site action links on the Sites tabs are misleading, dangerous

### ISSUE THREAD

**Issue by johnbillion** [stuttter/wp-user-profiles#38]
On a Multisite installation, the Sites tab on a user profile shows action links below each site listed (Edit, Dashboard, Spam, Archive, Deactivate, Delete, View). These actions affect the site, not the user nor the relationship the user has with the site, but this is not at all clear.

A client of mine deleted an entire site via the Delete link, thinking they were deleting the user from the site.

After some discussion with several people, I think the best thing is to remove _all_ the actions links from this screen, even the non-destructive ones, because it confuses users and it's not an appropriate context to show them. The link on the site name itself can remain, but the action links should all go.

**Comment by jennybeaumont** [comment]
@JJJ heya! Hope you don't mind me asking: any idea (even approximate) when v2.3 might be released?

**Comment by JJJ** [comment]
Just tagged 2.3.1. Sincerest apologies for letting this linger.

**Comment by jennybeaumont** [comment]
Thanks!
