### ISSUE TITLE
Consider adding a sub-navigation UI and API

### ISSUE THREAD

**Issue by JJJ** [stuttter/wp-user-profiles#43]
While this plugin has not achieved a _massive_ amount of popularity, it does have a bit of a cult following, and I'd like to propose an idea to its users that is also something that I would simply like to do personally.

The "Sections" API would get "Subsections", and it would look something like this:

## Sugar Calendar
<img width="600" alt="jjj-sc-2020-10-23 at 11 24 40@2x" src="https://user-images.githubusercontent.com/88951/97028934-5ee3f080-1522-11eb-8c4f-5383d90b0463.png">

## Easy Digital Downloads 3.0
<img width="961" alt="jjj-sc-2020-10-23 at 11 25 48@2x" src="https://user-images.githubusercontent.com/88951/97029103-905cbc00-1522-11eb-9b9f-3c1de7d18bec.png">

As you can see above, I've already implemented this into various other plugins with many more users than this plugin has. I am on-the-fence as to whether there is value in either showing or hiding the sub-navigation when there is only a single "General" item underneath each of them.

What is more important: consistency for the UI/UX, or not showing UI that isn't actually useful yet.

**Comment by JJJ** [comment]
Backwards compatibility is extremely important.

The way I imagine it working for this plugin is that meta-boxes without an explicit subsection would default to the first subsection, and that would include all of the existing meta-boxes in this plugin anyways as a sort-of litmus test.

Then add-ons for this plugin can start to register and add their own subsections to the primary sections.

In addition, for the multisite User Dashboard, these subsections can now become either sub-navigation items, or take over residency of the primary horizontal tabs.

**Comment by lkraav** [comment]
General idea: absolutely, yes.

1. Single tab should not be displayed.

2. Tabs: maybe we could just jump on WooCommerce styling bandwagon, since it's big and close to core.

![image](https://user-images.githubusercontent.com/147228/97078352-6f649b80-15f4-11eb-9ebf-35f5335b7522.png)

Then iterate towards enhancements like "more tab-like looks" in there + eventually making our way into WP core.

**Comment by JJJ** [comment]
I looked at Woo, and I think a lot of people are following what they're doing, but I _think_ this area of interest specifically is one where Woo may want to take inspiration from us (I think that about a lot of Woo things, frankly).

Those links are simply too easily missed by scanning eyes. And why does it allow admin notices in between them?

WordPress core also has the newer-style "tabs" that a few people have recommended switching to, but it looks more like a menu-bar to me, without having actual menus in it, so that's a no from me still.

**Comment by lkraav** [comment]
> WordPress core also has the newer-style "tabs" that a few people have recommended switching to

Screenshot for an example?

> where Woo may want to take inspiration from us

No doubt, I'd pitch in for a PR in that direction.

**Comment by JJJ** [comment]
## Add Themes

<img width="1279" alt="jjj-sc-2020-10-26 at 09 22 10@2x" src="https://user-images.githubusercontent.com/88951/97184310-c5f4e580-176c-11eb-8bcf-2b3416d4b666.png">

**Comment by JJJ** [comment]
PR ready to test. Included in the comments of that PR is a mu-plugin that I was testing with.

Eager to get this merged while it's fresh on my mind. Thank you in advance!

**Comment by JJJ** [comment]
## Site Dashboard
<img width="1163" alt="jjj-sc-2020-11-02 at 21 55 07@2x" src="https://user-images.githubusercontent.com/88951/97948403-1b755780-1d56-11eb-9ebb-f5b833700032.png">

## User Dashboard
<img width="1161" alt="jjj-sc-2020-11-02 at 21 53 11@2x" src="https://user-images.githubusercontent.com/88951/97948358-e79a3200-1d55-11eb-8d07-aba29ec4b904.png">

**Comment by lkraav** [comment]
Looks flawless :+1: 

`#profile-subnav` is custom CSS, or are we re-using someone's?

**Comment by JJJ** [comment]
Custom. Technically... it's mine, nicked from EDD3 and Sugar Calendar settings pages.
