### ISSUE TITLE
New strings can't be translated

### ISSUE THREAD

**Issue by knutsp** [stuttter/wp-user-profiles#49]
Strings like button text "Set new password", "Hide" and "Show" was translated (to Norwegian) at wp.org, and new language pack containing .po, .mo and .json files was received during update.

But the new strings added in latest version are still shown in English. Several sites, all checked sites so far.
![bilde](https://user-images.githubusercontent.com/1531128/98881872-3f8a1480-248b-11eb-9497-6d87dd404d6d.png)

**Comment by JJJ** [comment]
Sorry about this @knutsp. I'll release 2.5.0 tomorrow with this fix.

Thank you very much for bringing this to my attention. I really appreciate it!
