### ISSUE TITLE
Redirect core user edit requests to the plugin page?

### ISSUE THREAD

**Issue by bradyvercher** [stuttter/wp-user-profiles#5]
I keep running into an issue where plugins construct the user edit link manually instead of relying on `get_edit_user_link()`, so I almost always wind up on the core UI instead of the pretty interface provided by WP User Profiles. When making edits from the core UI, it caused issues on submission, which #4 should address, but I think it'd make sense to redirect requests from the core UI to the plugin page.

```php
<?php
add_action( 'load-user-edit.php', function() {
	$user_id = get_current_user_id();
	if ( ! empty( $_REQUEST['user_id'] ) ) {
		$user_id = absint( $_REQUEST['user_id'] );
	}

	$user_edit_url = add_query_arg( 'page', 'profile', wp_user_profiles_get_admin_area_url( $user_id ) );
	wp_safe_redirect( esc_url_raw( $user_edit_url ) );
	exit;
} );
```

[Here's an example in WooCommerce](https://github.com/woothemes/woocommerce/blob/efa19f799d6ebe81e92564b4a250070de6960c43/includes/admin/reports/class-wc-report-customer-list.php#L168) where the user edit link is being constructed manually (there are a few more instances in there as well).

**Comment by johnjamesjacoby** [comment]
Thanks for this. Definitely valid.
