### ISSUE TITLE
Some strings can still not be translated

### ISSUE THREAD

**Issue by knutsp** [stuttter/wp-user-profiles#52]
Strings like button text "Hide" and "Show" was translated (to Norwegian) at wp.org, and new language pack containing .po, .mo and .json files was received during update.

Strings in PHP was fixed, but not strings added through javascript. Shouldn't 'wp-i18n' added as dependency?

**Comment by JJJ** [comment]
@knutsp yes, you are correct. Because that was the first JavaScript file here with translations in it, I simply missed it.

Will get it fixed for the next release!
