### ISSUE TITLE
Funding services problem

### ISSUE THREAD

**Issue by knutsp** [stuttter/wp-user-profiles#54]
I tried both your funding links here, but neither of them worked for me (errors). PayPal worked.

**Comment by JJJ** [comment]
Hey @knutsp! You mean the ❤️ Sponsor links here on GitHub? If so, what happens when you try to use them?

I received your PayPal donation. Thank you, very much! I really appreciate it.

**Comment by JJJ** [comment]
I've disabled GitHub sponsorships for now. Gonna try something else eventually.

Thank you for the heads up!
