### ISSUE TITLE
Adding user to all sites removes super admin designation

### ISSUE THREAD

**Issue by chrisvanpatten** [stuttter/wp-user-profiles#56]
I've noticed that if I go into a super admin user's "Sites" tab, and use the Select All checkbox to assign a user to all sites, it removes their super admin status.

Steps to repro:

1. Create a user and mark as a super admin
2. Navigate to the "Sites" tab
3. Use the "select all" checkbox to select all sites, and assign them a role (I assigned admin)
4. Observe that the user is no longer marked as a super admin

**Comment by chrisvanpatten** [comment]
I did spend a bit of time looking at this and it appears to be related to this function:

https://github.com/stuttter/wp-user-profiles/blob/9db0216abd190e72a86f793f0f4ce3eba36e5a69/wp-user-profiles/includes/status.php#L150-L154

It appears this function is set to run when every tab is saved, but it's not totally clear to me why — shouldn't the super admin status only be toggled if you're on the Permissions tab, which is where the super admin checkbox lives?

**Comment by JJJ** [comment]
Good catch @chrisvanpatten. Revoking super admin access like that is definitely unintended.

I'm trying to think back to whether there was any specific reason this was put into the broader status scope, and am coming up empty, so it's likely a good idea to move its processing to a more specific action hook.
