### ISSUE TITLE
Saving on permissions tab changes permissions for all sites

### ISSUE THREAD

**Issue by chrisvanpatten** [stuttter/wp-user-profiles#70]
When you save while on the permissions tab, it changes the permissions for all sites.

Started with this:

<img width="508" alt="Screen Shot 2021-05-12 at 10 20 56 AM" src="https://user-images.githubusercontent.com/1231306/117991108-bfdee480-b30b-11eb-8fe8-e916f7417f41.png">

Hit "update", and it changes to:

<img width="504" alt="Screen Shot 2021-05-12 at 10 21 28 AM" src="https://user-images.githubusercontent.com/1231306/117991197-d2f1b480-b30b-11eb-9117-f2614c1f24d8.png">

Note that I hit update without making any changes to the form, but if I try changing any site to a different role it still resets so they all have the same role.

Somewhat interesting is that the `wp_X_capabilities` and `wp_X_user_level` user meta options don't seem to remain in sync when using this screen either. I wonder if this points to some data being held in memory which is preventing it from fully updating the role?

**Comment by chrisvanpatten** [comment]
I've also seen a variant of this where making changes in a user's roles ends up having no effect. I've only noticed that since 5.8 in particular so perhaps there's a regression unique to 5.8?

**Comment by JJJ** [comment]
Hey @chrisvanpatten 👋

I haven't been able to duplicate this yet, but I'll keep trying. I feel like the code _looks_ right to me, too:

https://github.com/stuttter/wp-user-profiles/blob/fc1659d9240e5501ebedb60d22cb0d2a6bfed045/wp-user-profiles/includes/sections/permissions.php#L62-L94

Stay in touch if you learn anything new, and I'll do the same 👍

**Comment by JJJ** [comment]
I discovered and fixed a save bug, but I'm unsure if it's related to what you're seeing here.

Pull the latest master and give it a try?

**Comment by chrisvanpatten** [comment]
@JJJ I actually think I incorrectly understood the scope of the issue; it actually appears that what's happening is that `switch_to_blog` isn't working correctly in our environment and so it causes changes to _only_ apply in site 1. We're actually seeing this behavior across multiple parts of our code, so I'm inclined to close this as something that we've broke in our code.

**Comment by chrisvanpatten** [comment]
I'm actually a little unsure now. I removed all plugins (except this one) from my install and the problem still persisted.

Ultimately, the only way I could find to fix this was inserting `$user->for_site( $blog_id );` right around here: https://github.com/stuttter/wp-user-profiles/blob/master/wp-user-profiles/includes/sections/permissions.php#L74

It seemed like the `$user->cap_key` was not changing with each `switch_to_blog` so it was always persisting the value back to `wp_capabilities` thus overwriting the main site and not changing anything else.

I can't figure out any reason why this would be happening… I've poked around stacktraces and tossed around debug statements but I'm also making my brain explode a little. I'm still not 100% convinced this is a wp-user-profiles bug (maybe a core bug?) but it seems to manifest pretty clearly here.

**Comment by chrisvanpatten** [comment]
Looks like, for some reason, when `wp_switch_roles_and_user` is being triggered by WP User Profiles' `switch_to_blog` call, it receives the same value for the new and old site IDs, even though the user is being switched to a different ID. That prevents the `for_site` call from being made by core, which is why my "custom" `for_site` inserted into this plugin resolved it. Will keep digging…

**Comment by chrisvanpatten** [comment]
@JJJ I think we've managed to reduce this down to a reproducible test case. We're able to repro this in vanilla core and in our custom code base. Pardon the mess.

```
<?php
add_action(
	'wp_network_dashboard_setup',
	'some_func'
);

function some_func() {
	// $user = get_user_by( 'id', 3 );
	// $user = wp_get_current_user();

	echo "start \r";
	echo 'current: ' . get_current_blog_id() . "\r";
	echo "user cap_key: {$user->cap_key}";

	switch_to_blog( 2 );
	echo "\r\r\r restore \r";
	echo 'current: ' . get_current_blog_id() . "\r";
	echo "user cap_key: {$user->cap_key}";

	restore_current_blog();
	echo "\r\r\r restore \r";
	echo 'current: ' . get_current_blog_id() . "\r";
	echo "user cap_key: {$user->cap_key}";
}
```

If you use the `wp_get_current_user` call to get your user object, the cap_key is set correctly:

```
start
current: 1
user cap_key: wp_capabilities

restore
current: 2
user cap_key: wp_2_capabilities

restore
current: 1
user cap_key: wp_capabilities
```

However if you use the user instance from `get_user_by`, the cap_key isn't changed for that instance:

```
start
current: 1
user cap_key: wp_capabilities

restore
current: 2
user cap_key: wp_capabilities

restore
current: 1
user cap_key: wp_capabilities
```

I believe this is because core only updates site/`cap_key` for the the _current_ user, via the `$current_user` global in the `wp_switch_roles_and_user` hook. Other instances aren't touched, and thus they preserve the `cap_key` that was set when the object was instantiated.

This is ultimately what causes the behavior we're experiencing: when you save a set of role changes, they're applied sequentially… but all do the `wp_capabilities` user meta key.

It's also worth observing that the `WP_User::update_user_level_from_caps` method is _not_ subject to this behavior because it constructs its meta key by using wpdb: `$wpdb->get_blog_prefix() . 'user_level'` This is not subject to the same issue because the global wpdb instance is updated during a `switch_to_blog` call.

**Comment by chrisvanpatten** [comment]
(That is to say, I believe the above is either a core bug or potentially a "wontfix", not a wp-user-profiles bug in particular — although one which could be worked around with an explicit `$user->for_site( $site_id )` call.

**Comment by JJJ** [comment]
That's awesome, and super helpful. PR imminent.
