### ISSUE TITLE
Suport 2FA-Plugin

### ISSUE THREAD

**Issue by ouun** [stuttter/wp-user-profiles#76]
@JJJ this is a very useful plugin, thanks a lot!
I would like to suggest that it supports the 2FA-Plugin (https://wordpress.org/plugins/two-factor/) by default.
Currently the settings land in the "Others" tab and it does not work as expected due JS issues. 

Kind regards,

Philipp

**Comment by ouun** [comment]
Hi @JJJ,
I hope you are doing great!
I don't want to generate any pressure. But I'd be very grateful for your estimate of when this could be implemented. Do you believe it would be possible this year?

Thanks and kind regards,

Philipp

**Comment by JJJ** [comment]
@ouun this year, yes!

I do _hope_ to give this plugin some attention in the coming weeks. 💟

**Comment by carstingaxion** [comment]
I gave this combination a try today, knowing about *this* particular issue.

During my investigation I found some obsolete usage of `check_admin_referrer()`, not *here* but, at [the other side](https://github.com/WordPress/two-factor/blob/master/class-two-factor-core.php#L1277).

I wasn't able to find any *not working* stuff at all. Even my console doesn't showed any errors, when updating one of the 2FA options or when I used the *Generate Verification Codes* Button. 

Could you please describe what you expected @ouun and what happened and where? ;)

**Comment by carstingaxion** [comment]
Ok, one thing, but it's not related to JS:

The 2FA Plugin gernerates an `admin_notice` with a link of `/wp-admin/profile.php#two-factor-backup-codes`, when you've no backup-codes left within your user-account.

In combination with `wp-user-profiles`, this link will go to `/wp-admin/users.php?page=profile#two-factor-backup-codes` which is not the needed page|tab of *Other*, where the settings are located. Unfortunately, I ad hoc had no idea on a nice solution yet.

**Comment by carstingaxion** [comment]
Ola @ouun,

thank you for taking the time.
>I guess the JS issue I mentioned is that the "Register New Key"-Button for FIDO-Keys does not work when WP User Profiles is active.

You're right. I'll have a look into it.

>The other improvement suggestion was to extract 2FA-Settings from the "Others"-Tab. Maybe "Acount" or a "Security"-Tab would be a more intuitive position.

Exactly what I had in mind, too. But didn't wrote it down.

**Comment by carstingaxion** [comment]
Fiddling with 

>the "Register New Key"-Button for FIDO-Keys

I was able to *bring back* the required javascripts from the **Two Factor** Plugin, by *just* enqueing them. 

```php
// Better compatibility for two-factor
// 
// Part1 : Bring back .js
add_action( 'admin_enqueue_scripts', function ( string $hook ) {
	
	if ('users_page_other' !== $hook )
		return;

	if ( ! class_exists('Two_Factor_FIDO_U2F_Admin')) {
		require_once TWO_FACTOR_DIR . 'providers/class-two-factor-fido-u2f-admin.php';
	}
	
	// this is missing, due to 'wp-user-profiles' different $hook global
	// luckily, we can just call it
	Two_Factor_FIDO_U2F_Admin::enqueue_assets( 'profile.php' );
}, 
// two-factor registers on 5 and enqueues at 10
0 );
```
For development puposes just loaded from a `mu-plugins` file for the moment.

But now, comes **Part 2**: 
```js
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://...') does not match the recipient window's origin ('null')
```
And this one I get even without `wp-user-profiles` enabled, as you can see from the window title of the first screenshot.

![Error while using the two-factor Plugin, without using the wp-user-profiles plugin](https://user-images.githubusercontent.com/198883/220297032-f518f308-931e-4335-98f5-c9fe282d9045.png)

![Error while using the two-factor Plugin AND using the wp-user-profiles plugin](https://user-images.githubusercontent.com/198883/220297286-4e58fcd7-e8cc-46b3-b745-95adb6e6abd5.png)




*No ideas, yet.*

**Comment by carstingaxion** [comment]
Going on with Part 3 : **Move 2FA into account tab**
remove_action( 'show_user_profile', array( 'Two_Factor_Core', 'user_two_factor_options' ) );
remove_action( 'edit_user_profile', array( 'Two_Factor_Core', 'user_two_factor_options' ) );
	
// fast & dirty, without own metabox
add_action( 'wp_user_profiles_password_metabox_after', array( 'Two_Factor_Core', 'user_two_factor_options' ) );

**Comment by carstingaxion** [comment]
Ola @JJJ . Where would be the best place to hold such compatibility code?

I would like open a PR with a cleaned and polished implementation.

**Comment by JJJ** [comment]
This is looking awesome so far!

@carstingaxion I think, use your best judgement! 😅 Since Two-Factor is a core WordPress initiative, treat it as if it were already merged and ready? We can conditionally hook/unhook it based on any criteria later (versions, activations, etc...)
