### ISSUE TITLE
core action 'user_profile_update_errors' is never called

### ISSUE THREAD

**Issue by carstingaxion** [stuttter/wp-user-profiles#82]
Dear @JJJ 

your plugin is a great piece of codework and I really appreciate using it.

Unfortunately right now, I have a problem using it in combination with a core action hook.

*Without your plugin activated*, when I visit `wp-admin/profile.php` and change my password, the [`user_profile_update_errors`](https://developer.wordpress.org/reference/hooks/user_profile_update_errors/) action is called, which I use to add some additional password-validation.

*With your plugin activated*, when I visit `wp-admin/users.php?page=account` and change my password, the `user_profile_update_errors` action never gets called, which is a problem (for me).

**Do you have any idea where to start looking for a solution?**

Best regards, Carsten.

**Comment by JJJ** [comment]
Hi @carstingaxion and thank you for finding this.

It is not intentional, has been fixed, and will be part of the next release. 💫

**Comment by carstingaxion** [comment]
Hello @JJJ,

even that I'm late with this comment, 
**you were incredibly fast, providing this fix.**

I'm hopping now for an *as similar fast* next release and
want to thank you very much!

Best Carsten

P.S. I would :heart: to see your workings on #71 also included in the next release.

**Comment by carstingaxion** [comment]
>It is not intentional, has been fixed, and will be part of the next release. 💫

Hello @JJJ ,

similar to #83 I would love to see this fix released into the wild.
Otherwise contributions wouldn't make any sense at all.

What's your plan about this?
